export const ProductData = [
  {
    name: "SanDisk SSD PLUS 1TB Internal SSD-...",
    url: "https://fakestoreapi.com/img/61U7T1koQqL._AC_SX679_.jpg",
    price: 699,
    category: "electronics",
  },
  {
    name: "Fjallraven - Foldsack No. 1 Backpack...",
    url: "https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg",
    price: 1099,
    category: "menCloths",
  },
  {
    name: "Silicon Power 256GB SSD 3D NAND A55...",
    url: "https://fakestoreapi.com/img/71kWymZ+c+L._AC_SX679_.jpg",
    price: 5000,
    category: "electronics",
  },
  {
    name: "WD 4TB Gaming Drive Works with Play...",
    url: "https://fakestoreapi.com/img/61mtL65D4cL._AC_SX679_.jpg",
    price: 25000,
    category: "electronics",
  },
  {
    name: "Acer SB220Q bi 21.5 inches Full HD ...",
    url: "https://fakestoreapi.com/img/81QpkIctqPL._AC_SX679_.jpg",
    price: 19000,
    category: "electronics",
  },
  {
    name: "Samsung 49-Inch CHG90 144Hz Curved ...",
    url: "https://fakestoreapi.com/img/81Zt42ioCgL._AC_SX679_.jpg",
    price: 70000,
    category: "electronics",
  },
  {
    name: "BIYLACLESEN Womens 3-in-1 Snowboar...",
    url: "https://fakestoreapi.com/img/51Y5NI-I5jL._AC_UX679_.jpg",
    price: 2599,
    category: `womenCloths`,
  },
  {
    name: `Lock and Love Women' s Removable Hoo...`,
    url: "https://fakestoreapi.com/img/81XH0e8fefL._AC_UY879_.jpg",
    price: 2599,
    category: `womenCloths`,
  },
  {
    name: "Rain Jacket Women Windbreaker Strip...",
    url: "https://fakestoreapi.com/img/71HblAHs5xL._AC_UY879_-2.jpg",
    price: 3333,
    category: `womenCloths`,
  },
  {
    name: "MBJ Women's Solid Short Sleeve Boat...",
    url: "https://fakestoreapi.com/img/71z3kpMAYsL._AC_UY879_.jpg",
    price: 799,
    category: `womenCloths`,
  },
  {
    name: "Opna Women's Short Sleeve Moisture...",
    url: "https://fakestoreapi.com/img/51eg55uWmdL._AC_UX679_.jpg",
    price: 699,
    category: `womenCloths`,
  },
  {
    name: "Mens Casual Premium Slim Fit T-Shir...",
    url: "https://fakestoreapi.com/img/71-3HjGNDUL._AC_SY879._SX._UX._SY._UY_.jpg",
    price: 300,
    category: `menCloths`,
  },
  {
    name: "DANVOUY Womens T Shirt Casual Cotto...",
    url: "https://fakestoreapi.com/img/61pHAEJ4NML._AC_UX679_.jpg",
    price: 999,
    category: `menCloths`,
  },
  {
    name: "Mens Cotton Jacket...",
    url: "https://fakestoreapi.com/img/71li-ujtlUL._AC_UX679_.jpg",
    price: 1155,
    category: `menCloths`,
  },
  {
    name: "Mens Casual Slim Fit...",
    url: "https://fakestoreapi.com/img/71YXzeOuslL._AC_UY879_.jpg",
    price: 900,
    category: `menCloths`,
  },
  {
    name: "John Hardy Women's Legends Naga Gol...",
    url: "https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg",
    price: 6950,
    category: `jewelry`,
  },
  {
    name: "Solid Gold Petite Micropave ...",
    url: "https://fakestoreapi.com/img/61sbMiUnoGL._AC_UL640_QL65_ML3_.jpg",
    price: 7500,
    category: `jewelry`,
  },
  {
    name: "White Gold Plated Princess...",
    url: "https://fakestoreapi.com/img/71YAIFU48IL._AC_UL640_QL65_ML3_.jpg",
    price: 3999,
    category: `jewelry`,
  },
  {
    name: "Pierced Owl Rose Gold Plated Stainl...",
    url: "https://fakestoreapi.com/img/51UDEzMJVpL._AC_UL640_QL65_ML3_.jpg",
    price: 10999,
    category: `jewelry`,
  },
  {
    name: "WD 2TB Elements Portable External H...",
    url: "https://fakestoreapi.com/img/61IBBVJvSDL._AC_SY879_.jpg",
    price: 999,
    category: `electronics`,
  },
];
